# xapian zmq vent
python /home/ubuntu12/linhao/xapian_weibo/zmq_workspace/xapian_zmq_vent.py >> /opt/project/weibo/cron/realtime/logs/xapian_zmq_vent.log
python /home/ubuntu12/linhao/xapian_weibo/zmq_workspace/xapian_zmq_vent.py >> /opt/project/weibo/cron/realtime/logs/xapian_zmq_vent.log
python /home/ubuntu12/linhao/xapian_weibo/zmq_workspace/xapian_zmq_vent.py >> /opt/project/weibo/cron/realtime/logs/xapian_zmq_vent.log
python /home/ubuntu12/linhao/xapian_weibo/zmq_workspace/xapian_zmq_vent.py >> /opt/project/weibo/cron/realtime/logs/xapian_zmq_vent.log
python /home/ubuntu12/linhao/xapian_weibo/zmq_workspace/xapian_zmq_vent.py >> /opt/project/weibo/cron/realtime/logs/xapian_zmq_vent.log
python /home/ubuntu12/linhao/xapian_weibo/zmq_workspace/xapian_zmq_vent.py >> /opt/project/weibo/cron/realtime/logs/xapian_zmq_vent.log
python /home/ubuntu12/linhao/xapian_weibo/zmq_workspace/xapian_zmq_vent.py >> /opt/project/weibo/cron/realtime/logs/xapian_zmq_vent.log
python /home/ubuntu12/linhao/xapian_weibo/zmq_workspace/xapian_zmq_vent.py >> /opt/project/weibo/cron/realtime/logs/xapian_zmq_vent.log
python /home/ubuntu12/linhao/xapian_weibo/zmq_workspace/xapian_zmq_vent.py >> /opt/project/weibo/cron/realtime/logs/xapian_zmq_vent.log
python /home/ubuntu12/linhao/xapian_weibo/zmq_workspace/xapian_zmq_vent.py >> /opt/project/weibo/cron/realtime/logs/xapian_zmq_vent.log
python /home/ubuntu12/linhao/xapian_weibo/zmq_workspace/xapian_zmq_vent.py >> /opt/project/weibo/cron/realtime/logs/xapian_zmq_vent.log
python /home/ubuntu12/linhao/xapian_weibo/zmq_workspace/xapian_zmq_vent.py >> /opt/project/weibo/cron/realtime/logs/xapian_zmq_vent.log
